version: '3'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/script/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    working_dir: /app/
    #command: ['mysql', '-u', 'root', '-pexample' , '<', 'schema.sql']
    #command: mysql -u root -pexample < schema.sql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8120:8080

  compiler:
    image: maven-xserver # or maven:3.6.0-jdk-11 if you run without IDE
    volumes:
      - ./:/root/ide
      - mavendata:/root/.m2:Z
      - appdata:/root/app:Z
    ports:
      - 8080:8080
      - 8081:8081
    command: bash
    stdin_open: true
    tty: true
    working_dir: /root/ide

volumes:
  mavendata:
    external:
      name: java_mavendata
  appdata:
    external:
      name: java_workplace
