version: '3'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/script/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    working_dir: /app/
    #command: ['mysql', '-u', 'root', '-pexample' , '<', 'schema.sql']
    #command: mysql -u root -pexample < schema.sql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8120:8080

  compiler:
    image: maven:3.6.0-jdk-11
    volumes:
      - ./ssoserver:/app
      - ./.m2/:/root/.m2/
    ports:
      - 8080:8080
      - 8081:8081
    command: bash
    stdin_open: true
    tty: true
    working_dir: /app/
