version: '3'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/script/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./mariadb/data:/var/lib/mysql
    working_dir: /app/
    #command: ['mysql', '-u', 'root', '-pexample' , '<', 'schema.sql']
    #command: mysql -u root -pexample < schema.sql
  
  tomcat:
    image: localhost:5001/tomcat9.0
    restart: always
    depends_on:
      - db
    ports:
      - 8082:8080
    volumes:
      - ./:/root/external

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

# docker run -it -p "8080:8080" -v "D:\\workspace:/root/external" -v "java_workspace:/root/" --rm --name compiler maven-xserver bash