version: '3'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/script/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    working_dir: /app/
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8120:8080

#  node1:
#    image: maven-xserver # or maven:3.6.0-jdk-11 if you run without IDE
#    volumes:
#      - appdata:/root/:Z
#    command: bash
#    stdin_open: true
#    tty: true
#    working_dir: /root
#  node2:
#    image: maven-xserver # or maven:3.6.0-jdk-11 if you run without IDE
#    volumes:
#      - appdata:/root/:Z
#    command: bash
#    stdin_open: true
#    tty: true
#    working_dir: /root
#
#  loadbalance:
#    image: nginx:stable
#    restart: always
#    depends_on:
#      - node1
#      - node2
#    volumes:
#      - ./site.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 8081:8081

  compiler:
    image: wingzzz2003/codeserver:3.9.0 # or maven:3.6.0-jdk-11 if you run without IDE
    #image: maven:3.6-jdk-11
    volumes:
      - /opt/data/codeserver:/root/
      - ./:/root/external
    ports:
      - "3000:3000"
      - "8080-8090:8080-8090"
      - "9000:9000"
    command: code-server
    stdin_open: true
    tty: true
    working_dir: /root
    
#  tomcat:
#    image: docker.ias.gov.mo:5001/tomcat9.0
#    ports:
#      - "8888:8080"
#    volumes:
#      - appdata:/root/:Z
#      - ./:/root/external

#in powershell
# set-variable -name DISPLAY -value 10.61.110.225:0.0
#docker exec -it -e DISPLAY=$DISPLAY docker-spring-boot-oauth_compiler_1 bash
